// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FlexSearch SQL Connector")>]
[<assembly: AssemblyDescriptionAttribute("FlexSearch SQL Connector")>]
[<assembly: AssemblyProductAttribute("FlexSearch")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (C) 2010 - 2016 - FlexSearch")>]
[<assembly: AssemblyFileVersionAttribute("0.9.1")>]
[<assembly: AssemblyVersionAttribute("0.9.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FlexSearch SQL Connector"
    let [<Literal>] AssemblyDescription = "FlexSearch SQL Connector"
    let [<Literal>] AssemblyProduct = "FlexSearch"
    let [<Literal>] AssemblyCopyright = "Copyright (C) 2010 - 2016 - FlexSearch"
    let [<Literal>] AssemblyFileVersion = "0.9.1"
    let [<Literal>] AssemblyVersion = "0.9.1"
